/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Apple Push Notification
 #	author : miyako
 #	2015/10/30
 #
 # --------------------------------------------------------------------------------*/



#include <stdio.h>
#include <stdlib.h>

#if VERSIONMAC
#include <sys/socket.h>
#include <netdb.h>
#include <openssl/ssl.h>
#include <arpa/inet.h>
#else
//BSD wrappers
#define bzero(s,n) memset(s,0x00,n)
#define bcopy(src,dest,n) memcpy(dest,src,n)
#define setenv(n,v,o)  _putenv_s(n,v)
#define close closesocket
#include <openssl/ssl.h>
#include <rpc.h>
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;
typedef wchar_t UniChar;
#endif

//default values	
#define APS_DEFAULT_PRODUCTION_PORT	(2195)
#define APS_DEFAULT_SANDBOX_PORT	(2195)
#define APS_DEFAULT_SANDBOX_URL		(const uint8_t*)"gateway.sandbox.push.apple.com"
#define APS_DEFAULT_PRODUCTION_URL	(const uint8_t*)"gateway.push.apple.com"

//these are protocol restrictions, keep private, hard coded
#define DEVICE_BINARY_SIZE			(32)
#define MAXPAYLOAD_SIZE				(256)

//the default will be production
#define APS_PROVISION_SANDBOX (1)
#define APS_PROVISION_PRODUCTION (2)

// --- Apple Push Notification
void APN_Get_sandbox_url(sLONG_PTR *pResult, PackagePtr pParams);
void APN_SET_PRODUCTION_URL(sLONG_PTR *pResult, PackagePtr pParams);
void APN_Get_production_url(sLONG_PTR *pResult, PackagePtr pParams);
void APN_Get_pem_path(sLONG_PTR *pResult, PackagePtr pParams);
void APN_SET_PEM_PATH(sLONG_PTR *pResult, PackagePtr pParams);
void APN_Push_Payload(sLONG_PTR *pResult, PackagePtr pParams);
void APN_SET_SANDBOX_PORT(sLONG_PTR *pResult, PackagePtr pParams);
void APN_SET_SANDBOX_URL(sLONG_PTR *pResult, PackagePtr pParams);
void APN_Get_sandbox_port(sLONG_PTR *pResult, PackagePtr pParams);
void APN_SET_PRODUCTION_PORT(sLONG_PTR *pResult, PackagePtr pParams);
void APN_Get_production_port(sLONG_PTR *pResult, PackagePtr pParams);
